version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: login_system_complete_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: login_system
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3309:3306"
    volumes:
      - login_system_complete_api:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  adv_lembrete_mysql_data: